exclude_patterns:
  - "ratiogenerator/src/main/java/io/github/mikolasan/ratiogenerator/LengthUnits.kt"
  - "ratiogenerator/src/main/java/io/github/mikolasan/ratiogenerator/MinLengthUnits.kt"
  - "ratiogenerator/src/main/java/io/github/mikolasan/ratiogenerator/RationGenerator.kt"