name: Android CI

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run gradle tests (littlefuzzy)
        run: ./gradlew :littlefuzzy:test

      - name: Run gradle tests (confermeifyoucan)
        run: ./gradlew :convertmeifyoucan:test
      
      - name: Run gradle tests (ratiogenerator)
        run: ./gradlew :ratiogenerator:test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            littlefuzzy/build/test-results/**/*.xml
            convertmeifyoucan/build/test-results/**/*.xml
            ratiogenerator/build/test-results/**/*.xml
